name = "WideBandDOA"
uuid = "10e811f0-8b13-4fd2-9f68-85477b038af4"
authors = ["Ray Kim <msca8h@naver.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
